---

- name: Provision Stack 
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - "./vars/network/bootstrap.yaml"
    - "./vars/network/cloudformation.yaml"
  roles:
    - "{{ stack }}"
