---
bootstrap:
        StackName: mediacorp
        VpcCidrBlock: 10.11.0.0/24
        Environment : production
        WebSubnetCIDR : 10.11.0.0/26
        AppSubnetCIDR : 10.11.0.64/26
        DataSubnetCIDR : 10.11.0.128/25
        StackAvailabilityZone : us-east-1a
        InstanceType : t2.micro
        AMI : ami-43ee9e79
        KeyPairName : build
